app:
  info:
    title: "Order Service API"
    description: "Order Service API Description"
    version: "v@project.version@"
  license:
    name: "Apache 2.0"
    url: "http://springdoc.org"
  externalDoc:
    description: "Order Service Wiki Documentation"
    url: "https://service.wiki.github.org/docs"

server:
  port: 8051
spring:
  application:
    name: order-service

  datasource:
    url: jdbc:oracle:thin:@192.168.1.50:32769/ORCLCDB.localdomain
    username: E_COMMERCE
    password: E_COMMERCE
    hikari:
      poolName: spring-hikari
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      max-lifetime: 3600000
      connection-timeout: 3000
      connection-test-query: "SELECT 1 FROM DUAL"
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.hbm2ddl.auto: none
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  kafka:
    producer:
      bootstrap-servers: 192.168.1.50:29092, 192.168.1.50:39092
    consumer:
      bootstrap-servers: 192.168.1.50:29092, 192.168.1.50:39092

  cache:
    type: redis
    redis:
      time-to-live: 1800000
    redis:
      host: 192.168.1.50
      port: 16379
      password: "Abcd123!@#"
      timeout: 3000

  zipkin:
    base-url: http://192.168.1.50:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: OOM, diskSpace, livenessState
        readiness:
          include: diskSpace, db, redis, readinessState
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, refresh, openapi, swaggerui"

test_var: value in dev
